AppBundle\Entity\Article:
    properties:
        title:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 100
                minMessage: "Min length is 2"
                maxMessage: "Max length is 100"
        content:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 50
                minMessage: "Min length is 2"
                maxMessage: "Max length is 100"
        autorId:
            - NotBlank: ~
            - NotNull: ~
            - AppBundle\Validator\Constraints\AutorExist: ~
        publicationDate:
            - DateTime: ~
            - NotNull: ~